version: "3.9"
services:
  rosbim:
    build:
      context: ..
      dockerfile: docker/Dockerfile.base
    container_name: rosbim_base
    image: fhi-git.fraunhofer.it:5050/construction-robotics/concert/rosbim:humble
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    network_mode: host
    privileged: true
    volumes:
      - ../:/rosbim/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
