version: "3.9"
services:
  rosbim:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    container_name: rosbim_app
    image: fhi-git.fraunhofer.it:5050/construction-robotics/concert/rosbim:app
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
    network_mode: host
    privileged: true
    volumes:
      - ../:/rosbim/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
    command:
      terminator